name: Unit Test
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup secrets file
        shell: bash
        env:
          OPEN_AI_API_KEY: "${{ secrets.OPEN_AI_API_KEY }}"
        run: |
          mkdir -p src/.steamship/; echo -e "openai_api_key =" "\"""$OPEN_AI_API_KEY""\"" > src/.steamship/secrets.toml

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8.x"

      - name: Install Virtualenv
        run: |
          python3 -m venv .venv
      - name: Activate Virtualenv
        run: |
          source .venv/bin/activate
      - name: Install Dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Install Development Dependencies
        run: |
          python -m pip install -r requirements.dev.txt
      - name: Run unit tests
        run: |
          pytest test/test_unit.py
